DROP TABLE IF EXISTS RENGLONESRECIBOS;
DROP TABLE IF EXISTS RECIBOS;
DROP TABLE IF EXISTS DETALLESPREMIOSDEDUCCIONES;
DROP TABLE IF EXISTS TOTALESPREMIOSDEDUCCIONES;
DROP TABLE IF EXISTS MOVIMIENTOSCUENTACORRIENTE;
DROP TABLE IF EXISTS NUMEROSSORTEADOS;
DROP TABLE IF EXISTS SORTEOSLOTERIAS;
DROP TABLE IF EXISTS PREMIOS;
DROP TABLE IF EXISTS sorteo;
DROP TABLE IF EXISTS sorteos;


ALTER TABLE PARAMETROS ALTER COLUMN valor varchar(10000)